name: tests

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go test ./...

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false
      - name: Check examples
        run: |
          printf "Executing equivalence tests on example directory\n\n"
          go run main.go update --goldens=examples/example_golden_files --tests=examples/example_test_cases
          printf "\n\nFinished executing equivalence tests on example directory\n\n"
          
          if [[ `git status --porcelain` ]]; then
            printf "Found modified example test cases with no updated golden files\n"
            printf 'Please run `go run main.go update --goldens=examples/example_golden_files --tests=examples/example_test_cases` and commit the changes\n'

            git diff

            exit 1
          fi
