name: tests

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go build -v .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - run: go test ./...

  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0
      - run: go run main.go --goldens=examples/example_golden_files --tests=examples/example_test_cases -update
      - run: |
          if [[ `git status --porcelain` ]]; then
            echo "found modified example test cases with no update golden files"
            echo "please run `go run main.go --goldens=examples/example_golden_files --tests=examples/example_test_cases -update` and commit the changes"
            exit 1
          fi
